name: ArmTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy RG using ARM Template GitHub Action
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: d86c85ff-5c6c-4054-bc3c-b549ca9f2795
          region: eastus
          template: ./arm-templates/rg.json
          deploymentName: rg-GitHub-Deploy

      - name: Deploy SA using ARM Template GitHub Action
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-GitHub
          subscriptionId: d86c85ff-5c6c-4054-bc3c-b549ca9f2795
          template: ./arm-templates/storageaccount.json
          parameters: 
            ./arm-templates/storageaccount.parameters.json
            storageAccountName= hkdas4001
            location= "eastus"
          deploymentName: SA-DeployARM-Action
          deploymentMode: incremental


